### PR TITLE
dev-lang/rust: add beta channel ebuild

### PR DESCRIPTION
**Pull request by stefson**
this is work in progress due to the added patch. It seems that it caused a few hickups here and there, for instance it adds roughly 30% on time to emerge, but it greatly reduces the amount of libraries installed.

### CODE REVIEW

**Comment by stefson** [comment]
```
250616 -rw------- 1 root users 256623420 11. Okt 19:50 rust-999.tbz2
77248 -rw------- 1 root users  79096852 11. Okt 21:03 rust-999.tbz2
```
first without the patch, second with the patch.

**Comment by stefson** [comment]
It should be good to go, when 65474 has been merged to the master branch. 

```
77240 -rw------- 1 root users  79087185 22. Okt 13:00 rust-999.tbz2
```

**Comment by stefson** [comment]
pr65474 has been merged per https://github.com/rust-lang/rust/commit/8e0007f829661e57d008d2e908c95f6e84b04b25.patch

@cnd

**Comment by cnd** [comment]
@stefson is it fully ready for it?

**Comment by stefson** [comment]
ebuild is working just fine, rust compiler runtime tested as well: 

```
rustc 1.39.0-dev (224f0bc90 2019-10-15)
binary: rustc
commit-hash: 224f0bc90c010b88ca6ec600c9b02f6e3638d78e
commit-date: 2019-10-15
host: x86_64-unknown-linux-gnu
release: 1.39.0-dev
LLVM version: 9.0
```

the patch needs to be removed when there's a rust-1.40beta available, since it's been merged in the master branch only.

**Pull request merged**
