### PR TITLE
dev-lang/rust-std: initial ebuild

### PR DESCRIPTION
**Pull request by stefson**
todo: fix file collisions

### CODE REVIEW

**Comment by stefson** [comment]
A quick test shows, it's all up and working as intended, nicely integrated into rust-bin:

```
root@gentoo-rpi2-glibc # equery f rust-std
 * Searching for rust-std ...
 * Contents of dev-lang/rust-std-1.36.0:
/opt
/opt/rust-bin-1.36.0
/opt/rust-bin-1.36.0/lib
/opt/rust-bin-1.36.0/lib/rustlib
/opt/rust-bin-1.36.0/lib/rustlib/manifest-rust-std-thumbv7neon-unknown-linux-gnueabihf
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib/liballoc-c29abd529ba4452b.rlib
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib/libbacktrace_sys-54463ae5adae3649.rlib
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib/libcompiler_builtins-38e90baf978bc428.rlib
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib/libcore-5594cb4f559bc761.rlib
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib/libgetopts-50d6bab7df588609.rlib
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib/libhashbrown-51f4300e102199f5.rlib
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib/liblibc-505bcee45aafb736.rlib
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib/libpanic_abort-a6724571446cdab6.rlib
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib/libpanic_unwind-57306b8ed3378a0e.rlib
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib/libproc_macro-057420995d29760a.rlib
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib/librustc_demangle-d99667b199a9875a.rlib
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib/librustc_std_workspace_alloc-b3ccf1f7737a6a91.rlib
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib/librustc_std_workspace_core-895383a3232f6572.rlib
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib/libstd-2dc1ba48239659d3.rlib
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib/libstd-2dc1ba48239659d3.so
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib/libterm-c9d91925876437f2.rlib
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib/libterm-c9d91925876437f2.so
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib/libtest-e8fbf0b14816ca0e.rlib
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib/libtest-e8fbf0b14816ca0e.so
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib/libunicode_width-913b30c2987aa8da.rlib
/opt/rust-bin-1.36.0/lib/rustlib/thumbv7neon-unknown-linux-gnueabihf/lib/libunwind-157c37a3ceb78853.rlib
```

**Comment by cnd** [comment]
khm is it additional std for something? rust bin is coming with std I guess, @stefson ?

**Comment by stefson** [comment]
Yes, it's an additional std-library. From rust-1.35.0 on it's mandantory if you want to use neon instructions for compiling firefox.

**Comment by stefson** [comment]
Also this is the way to go, if you want to add cross-compile abilities to rust. I might add more rust-std's in the future.

**Pull request merged**
