### PR TITLE
Build using installed rust

### PR DESCRIPTION
**Pull request by wthrowe**
Since rust doesn't use snapshots anymore and builds from the previous stable compiler, Gentoo should start using the installed version rather than downloading a binary to bootstrap from.

I ran into this while investigating https://bugs.gentoo.org/show_bug.cgi?id=592016

A first install of rust will now require bootstrapping from rust-bin, so newer versions of that will need to be added to the main tree if this ebuild is moved there.

For ease of comparison, here's a diff from the ebuild in the main tree:
```diff
@@ -24,16 +24,12 @@
 fi
 
 STAGE0_VERSION="1.$(($(get_version_component_range 2) - 1)).0"
-RUST_STAGE0_amd64="rustc-${STAGE0_VERSION}-x86_64-unknown-linux-gnu"
-RUST_STAGE0_x86="rustc-${STAGE0_VERSION}-i686-unknown-linux-gnu"
+NEXT_VERSION="1.$(($(get_version_component_range 2) + 1)).0"
 
 DESCRIPTION="Systems programming language from Mozilla"
 HOMEPAGE="http://www.rust-lang.org/"
 
-SRC_URI="https://static.rust-lang.org/dist/${SRC} -> rustc-${PV}-src.tar.gz
-       amd64? ( https://static.rust-lang.org/dist/${RUST_STAGE0_amd64}.tar.gz )
-       x86? ( https://static.rust-lang.org/dist/${RUST_STAGE0_x86}.tar.gz )
-"
+SRC_URI="https://static.rust-lang.org/dist/${SRC} -> rustc-${PV}-src.tar.gz"
 
 LICENSE="|| ( MIT Apache-2.0 ) BSD-1 BSD-2 BSD-4 UoI-NCSA"
 
@@ -45,24 +41,25 @@
                <sys-devel/llvm-3.9.0:=[multitarget] )
 "
 
+# We can't depend on virtual/rust for building because portage (as of
+# 2.3.0) gets confused by the circular dependency when trying to
+# upgrade.
 DEPEND="${RDEPEND}
        ${PYTHON_DEPS}
        >=dev-lang/perl-5.0
        clang? ( sys-devel/clang )
+       || (
+               ( >=dev-lang/rust-bin-${STAGE0_VERSION}:stable
+                 <dev-lang/rust-bin-${NEXT_VERSION}:stable )
+               ( >=dev-lang/rust-${STAGE0_VERSION}:stable
+                 <dev-lang/rust-${NEXT_VERSION}:stable )
+       )
 "
 
 PDEPEND=">=app-eselect/eselect-rust-0.3_pre20150425"
 
 S="${WORKDIR}/${MY_P}"
 
-src_unpack() {
-       unpack "rustc-${PV}-src.tar.gz" || die
-       mkdir "${MY_P}/dl" || die
-       local stagename="RUST_STAGE0_${ARCH}"
-       local stage0="${!stagename}"
-       cp "${DISTDIR}/${stage0}.tar.gz" "${MY_P}/dl/" || die "cp stage0"
-}
-
 src_prepare() {
        find mk -name '*.mk' -exec \
                 sed -i -e "s/-Werror / /g" {} \; || die
@@ -71,6 +68,22 @@
 }
 
 src_configure() {
+       # In order to compile itself, rustc needs to be passed a special
+       # argument to allow the use of unstable language features.  This
+       # argument varies by version, so we have to tell the build system
+       # whether this is a recompile or an upgrade.
+       local local_rebuild
+       local installed_version="$("${EPREFIX}/usr/bin/rustc" --version)" || die
+       case "${installed_version}" in
+               "rustc ${PV}") local_rebuild=--enable-local-rebuild ;;
+               "rustc ${STAGE0_VERSION}") ;;
+               *)
+                       eerror "Selected rust (${installed_version}) cannot build"
+                       eerror "version ${PV}.  Please use version ${STAGE0_VERSION}"
+                       eerror "or ${PV}."
+                       die "Incompatible rust selected"
+       esac
+
        export CFG_DISABLE_LDCONFIG="notempty"
 
        "${ECONF_SOURCE:-.}"/configure \
@@ -83,6 +96,9 @@
                --default-ar=$(tc-getBUILD_AR) \
                --python=${EPYTHON} \
                --disable-rpath \
+               --enable-local-rust \
+               --local-rust-root="${EPREFIX}/usr" \
+               ${local_rebuild} \
                $(use_enable clang) \
                $(use_enable debug) \
                $(use_enable debug llvm-assertions) \
```

### CODE REVIEW

**Comment by wthrowe** [comment]
The new breakage appears to be related to Gentoo using a nonstandard `--libdir`, which has confused rust's build system before.  I've added a patch here and verified that I can now upgrade rust from 1.10.0.  A test of reinstalling is in progress, and I would have expected it to fail by now if it was going to.

**Comment by wthrowe** [comment]
With the latest minor change I can build rust-1.11.0 from rust-bin-1.11.0.  Portage even figures out that it needs to install the -bin package first and then removes it if `emerge --depclean` is run (although it doesn't leave me with a valid rust eselected).

I think this ebuild is working now.  I will look into upstreaming the build system patch.

**Comment by mpkh** [comment]
@cardoe what do you think about it

**Comment by devurandom** [comment]
Instead of executing `rustc --version`, wouldn't `best_version dev-lang/rust` be the correct way to get the current version of Rust?

**Comment by wthrowe** [comment]
We need to check which version of rust is called by `/usr/bin/rustc`.  That could be any slot of rust or rust-bin depending on what the user has chosen with `eselect`.

**Comment by mpkh** [comment]
@wthrowe is it currently ready for testing?

**Comment by wthrowe** [comment]
Yes, please test.

**Pull request merged**
