### PR TITLE
Use virtual/rust instead of dev-lang/rust

### PR DESCRIPTION
**Pull request by suhr**
Moved from https://github.com/Heather/gentoo-rust/pull/158.

### CODE REVIEW

**Comment by suhr** [comment]
I have no idea what's wrong with it.

**Comment by Heather** [comment]
@suhr seems like missing KEYWORDS https://github.com/gentoo/gentoo-rust/pull/32/files#diff-6dbb4407370d4e58a499ea2b4818bd23R13

**Comment by Heather** [comment]
with `>=virtual/rust-1.1.0` -> `virtual/rust:*` why not `>=virtual/rust-1.1.0:*`

**Comment by Heather** [comment]
@suhr looks good now, thanks!

**Comment by suhr** [comment]
Btw, can you somehow make gentoo/gentoo-rust the main repo? Gh thinks it's a fork.

**Comment by Heather** [comment]
@suhr yes I can

**Pull request merged**
