### PR TITLE
Updates for Rust 1.7.0

### PR DESCRIPTION
**Pull request by cardoe**
So I've done a bit of digging with the aim of getting Rust support into the main tree. These are the changes that I believe are necessary to get dev-lang/rust-1.7.0 into the tree but I would like the overlay maintainers to review each of these patches because you have more experience.

### CODE REVIEW

**Comment by cardoe** [comment]
@jauhien, @Heather and @gentoo90: Hoping you all have some feedback when you have time.

**Comment by williamh** [comment]
I think that when this goes in the tree we should use 1.7.0 as the version number and not 1.7.0-r1 since 1.7.0 doesn't exist in the tree.

**Comment by cardoe** [comment]
@williamh of course. But the overlay already had 1.7.0 so that needed a bump.

**Comment by Heather** [comment]
@cardoe thank you

**Comment by cardoe** [comment]
@Heather You were ok with dropping the postfix that we do?

**Comment by Heather** [comment]
@cardoe someone else added it there with some reason, maybe @jauhien but currently it's really not clear so we will restore if we will understand that we need it there, also if we will need to revert it - comment will be helpful

**Comment by cardoe** [comment]
Thanks @Heather. Good to know.

**Pull request merged**
