### PR TITLE
dev-lang/rust-9999: raise llvm slot to 9 

### PR DESCRIPTION
**Pull request by stefson**
@o01eg @cnd asking for a review: 

should we follow upstreams choice of llvm-9? 

Also: does my code do that? I'm not absolutly sure :-)

### CODE REVIEW

**Comment by o01eg** [comment]
I haven't yet tested it, but doesn't it work with system-llvm and llvm-8.0.1?

**Comment by stefson** [comment]
hmm, I haven't tested yet either. The question was more if we should follow upstream and force llvm-9

**Comment by cnd** [comment]
```diff
	<sys-devel/llvm-9:=
"
-LLVM_MAX_SLOT=8
+LLVM_MAX_SLOT=9
```

That line is confusing in that diff `<sys-devel/llvm-9:=`
I understand it's only for system llvm? but there should be equal changes for both conditions
I don't think we should force 9 if it's still working with 8 but that needs testing, however testing in not highest priority and can be done by someone else so if you're sure that it works with 9 and doubt about 8 I'm not against dropping 8 support until someone else will need/test it and approve that it does work.

**Comment by cnd** [comment]
looks fine for me

**Comment by o01eg** [comment]
It works with llvm-8.0.1. I've successfully tried to compile and run veloren. The only issue is `sanitize` doesn't work with `system-llvm`.

**Pull request merged**
