### PR TITLE
dev-utils/racer: Remove vim and emacs plugins installation.

### PR DESCRIPTION
**Pull request by o01eg**
ToDo: create ebuilds for them.

### CODE REVIEW

**Comment by stratact** [comment]
Any progress on this? I need Racer to build again in order to use it.

**Comment by Heather** [comment]
@o01eg @stratact does this pull request fix something? I'm waiting for actual ebuilds for vim/emacs modes in case of removal their support from here, shouldn't I?

**Comment by o01eg** [comment]
I've added vim support but I don't use emacs so I hope someone else create and test ebuild for https://github.com/racer-rust/emacs-racer.

**Comment by stratact** [comment]
Vim is what I use, so for me I'm good. :+1:

**Comment by Heather** [comment]
it's even already added

**Pull request merged**
