### PR TITLE
Add support for WebAssembly

### PR DESCRIPTION
**Pull request by o01eg**
Enables wams32-unknown-unknown target.
Enables installation LLD linker.
Works only with `RUSTFLAGS="-C linker=lld"`. I'm not sure how to fix it.

### CODE REVIEW

**Comment by cnd** [comment]
@gentoo90 @gibix may you verify this?

**Comment by gentoo90** [comment]
Build fails if `network-sandbox` feature is enabled, because it tries to download crates from crates.io, just like in #340. @o01eg could you add `RESTRICT="network-sandbox"` to the ebuild?

**Comment by o01eg** [comment]
@gentoo90 Thanks. Fixed.
Is it something new for live ebuilds?

**Comment by cnd** [comment]
now good?

**Comment by gentoo90** [comment]
Well, it emerged successfully but it fails to build [wasm hello world](https://github.com/rust-lang-nursery/rust-wasm/blob/master/src/hello-world.md):
```
$ LANG=C cargo build --target=wasm32-unknown-unknown --release
   Compiling wasm-demo v0.1.0 (file:///home/user/projects/rust/wasm-demo)
error: linking with `x86_64-pc-linux-gnu-gcc` failed: exit code: 1
  |
  = note: "x86_64-pc-linux-gnu-gcc" "-flavor" "wasm" "-L" "/usr/lib64/rust-9999/rustlib/wasm32-unknown-unknown/lib" "/home/user/projects/rust/wasm-demo/target/wasm32-unknown-unknown/release/deps/wasm_demo.wasm_demo0-c597a390c7feb3f4763db6bd9879dd69.rs.rcgu.o" "-o" "/home/user/projects/rust/wasm-demo/target/wasm32-unknown-unknown/release/deps/wasm_demo.wasm" "/home/user/projects/rust/wasm-demo/target/wasm32-unknown-unknown/release/deps/wasm_demo.crate.allocator.rcgu.o" "-L" "/home/user/projects/rust/wasm-demo/target/wasm32-unknown-unknown/release/deps" "-L" "/home/user/projects/rust/wasm-demo/target/release/deps" "-L" "/usr/lib64/rust-9999/rustlib/wasm32-unknown-unknown/lib" "/usr/lib64/rust-9999/rustlib/wasm32-unknown-unknown/lib/libstd-f6fd575b100aedb5.rlib" "/usr/lib64/rust-9999/rustlib/wasm32-unknown-unknown/lib/libpanic_abort-74f6025ac6baf0a6.rlib" "/usr/lib64/rust-9999/rustlib/wasm32-unknown-unknown/lib/libunwind-6532930d2cb67081.rlib" "/usr/lib64/rust-9999/rustlib/wasm32-unknown-unknown/lib/liblibc-738f2f0e3ca1a51d.rlib" "/usr/lib64/rust-9999/rustlib/wasm32-unknown-unknown/lib/liballoc_system-ac0a59a46f283e03.rlib" "/usr/lib64/rust-9999/rustlib/wasm32-unknown-unknown/lib/libdlmalloc-65f47949bbea58e2.rlib" "/usr/lib64/rust-9999/rustlib/wasm32-unknown-unknown/lib/liballoc-20e96f335787e38a.rlib" "/usr/lib64/rust-9999/rustlib/wasm32-unknown-unknown/lib/libcore-920067538be3639e.rlib" "/usr/lib64/rust-9999/rustlib/wasm32-unknown-unknown/lib/libcompiler_builtins-61e79a7317148bdb.rlib" "--no-threads" "-z" "stack-size=1048576" "--allow-undefined" "--no-entry"
  = note: x86_64-pc-linux-gnu-gcc: error: wasm: No such file or directory
          x86_64-pc-linux-gnu-gcc: error: unrecognized command line option '-flavor'; did you mean '-flto'?
          x86_64-pc-linux-gnu-gcc: error: unrecognized command line option '--no-threads'; did you mean '--no-ltrans'?
          x86_64-pc-linux-gnu-gcc: error: unrecognized command line option '--allow-undefined'; did you mean '--all-warnings'?
          x86_64-pc-linux-gnu-gcc: error: unrecognized command line option '--no-entry'; did you mean '-mno-fentry'?
          

error: Could not compile `wasm-demo`.

To learn more, run the command again with --verbose.
```

I don't know if it's because of the ebuild or the rust itself.

**Comment by gibix** [comment]
I think that the linker should target something like `-L /usr/lib64/rust-9999/rustlib/wasm32-unknown-unknown/bin/lld`.

**Comment by o01eg** [comment]
@gentoo90 Could you check if it works when you set `RUSTFLAGS="-C linker=lld"`?

**Comment by gentoo90** [comment]
> Could you check if it works when you set RUSTFLAGS="-C linker=lld"?

Yup, compiled the crate successfully.
```
$ RUSTFLAGS="-C linker=lld" cargo build --target=wasm32-unknown-unknown --release
   Compiling wasm-demo v0.1.0 (file:///home/user/projects/rust/wasm-demo)
    Finished release [optimized] target(s) in 0.75s
```

**Pull request merged**
